/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.simulatorHealthCody.view1;

/**
 *
 * @author Mateo Ávila ESPE
 */
public class InventoryWindow extends javax.swing.JFrame {

    /**
     * Creates new form InventoryWindow
     */
    public InventoryWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddProduct = new javax.swing.JButton();
        btnSearchProduct = new javax.swing.JButton();
        btnModificProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        btnViewInventory = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtProduct = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btnAddProduct.setText("Agregar Producto");
        jPanel1.add(btnAddProduct);
        btnAddProduct.setBounds(220, 180, 220, 50);

        btnSearchProduct.setText("Buscar Producto");
        jPanel1.add(btnSearchProduct);
        btnSearchProduct.setBounds(450, 180, 220, 50);

        btnModificProduct.setText("Modificar Producto");
        jPanel1.add(btnModificProduct);
        btnModificProduct.setBounds(220, 240, 220, 50);

        btnDeleteProduct.setText("Eliminar Producto");
        jPanel1.add(btnDeleteProduct);
        btnDeleteProduct.setBounds(450, 240, 220, 50);

        btnViewInventory.setText("Ver Inventario");
        jPanel1.add(btnViewInventory);
        btnViewInventory.setBounds(350, 310, 220, 50);

        btnAccept.setText("Aceptar");
        jPanel1.add(btnAccept);
        btnAccept.setBounds(450, 370, 220, 40);

        btnReturn.setText("Regresar");
        jPanel1.add(btnReturn);
        btnReturn.setBounds(380, 450, 130, 40);

        jLabel2.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 48)); // NOI18N
        jLabel2.setText("Inventario");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 100, 400, 60);
        jPanel1.add(txtProduct);
        txtProduct.setBounds(220, 370, 220, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/simulatorHealthCody/view1/InventoryIMG.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnModificProduct;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnSearchProduct;
    private javax.swing.JButton btnViewInventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtProduct;
    // End of variables declaration//GEN-END:variables
}
