/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.simulatorHealthCody.view;

import com.google.gson.Gson;
import ec.edu.espe.simulatorHealthCody.model.Product;
import ec.edu.espe.simulatorHealthCody.view.AddProductWindow;
import ec.edu.espe.simulatorHealthCody.view.AddProductWindow;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Mateo Ávila ESPE
 */
public class InventoryWindow extends javax.swing.JFrame {

    /**
     * Creates new form InventoryWindow
     */
    public InventoryWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        ButtonGroup bG = new ButtonGroup();
        bG.add(rdbSearch);
        bG.add(rdbModific);
        bG.add(rdbDelete);
        txtProduct.setVisible(false);
        btnAccept.setVisible(false);
        lblModificD.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddProduct = new javax.swing.JButton();
        btnViewInventory = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtProduct = new javax.swing.JTextField();
        rdbSearch = new javax.swing.JRadioButton();
        rdbModific = new javax.swing.JRadioButton();
        rdbDelete = new javax.swing.JRadioButton();
        lblModificD = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        btnAddProduct.setText("Agregar Producto");
        jPanel1.add(btnAddProduct);
        btnAddProduct.setBounds(120, 130, 220, 50);

        btnViewInventory.setText("Ver Inventario");
        jPanel1.add(btnViewInventory);
        btnViewInventory.setBounds(120, 200, 220, 50);

        btnAccept.setText("Aceptar");
        jPanel1.add(btnAccept);
        btnAccept.setBounds(410, 290, 200, 40);

        btnReturn.setText("Regresar");
        jPanel1.add(btnReturn);
        btnReturn.setBounds(300, 350, 150, 40);

        jLabel2.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 48)); // NOI18N
        jLabel2.setText("Inventario");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 10, 400, 60);
        jPanel1.add(txtProduct);
        txtProduct.setBounds(120, 290, 220, 40);

        rdbSearch.setText("Buscar Producto");
        jPanel1.add(rdbSearch);
        rdbSearch.setBounds(410, 130, 200, 40);

        rdbModific.setText("Modificar Producto");
        jPanel1.add(rdbModific);
        rdbModific.setBounds(410, 180, 200, 40);

        rdbDelete.setText("Eliminar Producto");
        jPanel1.add(rdbDelete);
        rdbDelete.setBounds(410, 230, 200, 40);

        lblModificD.setText("Dato a modificar");
        lblModificD.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                lblModificDComponentHidden(evt);
            }
        });
        jPanel1.add(lblModificD);
        lblModificD.setBounds(120, 340, 140, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/simulatorHealthCody/images/InventoryIMG.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblModificDComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblModificDComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModificDComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAccept;
    public javax.swing.JButton btnAddProduct;
    public javax.swing.JButton btnReturn;
    public javax.swing.JButton btnViewInventory;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblModificD;
    public javax.swing.JRadioButton rdbDelete;
    public javax.swing.JRadioButton rdbModific;
    public javax.swing.JRadioButton rdbSearch;
    public javax.swing.JTextField txtProduct;
    // End of variables declaration//GEN-END:variables
}
