/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.simulatorHealthCody.view;

import ec.edu.espe.simulatorHealthCody.controller.LoginCustomerController;


/**
 *
 * @author Mateo Ávila ESPE
 */
public class LoginCustomer extends javax.swing.JFrame {
    LoginCustomerController controller = new LoginCustomerController(this);
    /**
     * Creates new form PrincipalWindow
     */
    public LoginCustomer() {

        initComponents();
        this.setLocationRelativeTo(null);
        rdbCustomer.setVisible(false);
        rdbEmployee.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectRegistry = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblAdminLogin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        txpPassword = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        rdbEmployee = new javax.swing.JRadioButton();
        rdbCustomer = new javax.swing.JRadioButton();
        imgWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        lblAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblAdminLogin.setText("¿Eres administrador?");
        lblAdminLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdminLoginMouseClicked(evt);
            }
        });
        jPanel1.add(lblAdminLogin);
        lblAdminLogin.setBounds(720, 360, 140, 16);

        jLabel5.setFont(new java.awt.Font("Apple SD Gothic Neo", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingreso para usuarios");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(580, 120, 260, 32);

        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("Usuario:");
        jPanel1.add(lblUserName);
        lblUserName.setBounds(580, 180, 70, 16);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(690, 390, 80, 30);

        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Contraseña:");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(580, 240, 90, 16);

        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setText("Regístrate");
        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterMouseClicked(evt);
            }
        });
        jPanel1.add(lblRegister);
        lblRegister.setBounds(780, 300, 70, 16);
        jPanel1.add(txpPassword);
        txpPassword.setBounds(580, 260, 260, 24);
        jPanel1.add(txtUserName);
        txtUserName.setBounds(580, 200, 260, 24);

        rdbEmployee.setBackground(new java.awt.Color(102, 102, 102));
        SelectRegistry.add(rdbEmployee);
        rdbEmployee.setForeground(new java.awt.Color(255, 255, 255));
        rdbEmployee.setText("Empleado");
        rdbEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(rdbEmployee);
        rdbEmployee.setBounds(750, 320, 88, 28);

        rdbCustomer.setBackground(new java.awt.Color(102, 102, 102));
        SelectRegistry.add(rdbCustomer);
        rdbCustomer.setForeground(new java.awt.Color(255, 255, 255));
        rdbCustomer.setText("Cliente");
        rdbCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(rdbCustomer);
        rdbCustomer.setBounds(610, 320, 110, 30);

        imgWallpaper.setForeground(new java.awt.Color(255, 255, 255));
        imgWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/simulatorHealthCody/images/PrincipalWindowIMG.png"))); // NOI18N
        imgWallpaper.setText("jLabel1");
        jPanel1.add(imgWallpaper);
        imgWallpaper.setBounds(0, 0, 940, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String userName, password;
        userName = txtUserName.getText();
        password = txpPassword.getText();
        controller.login(userName, password);
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
        rdbCustomer.setVisible(true);
        rdbEmployee.setVisible(true);
    }//GEN-LAST:event_lblRegisterMouseClicked

    private void rdbCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCustomerActionPerformed
        controller.pressCustomer();
    }//GEN-LAST:event_rdbCustomerActionPerformed

    private void rdbEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEmployeeActionPerformed
        controller.pressEmployee();
    }//GEN-LAST:event_rdbEmployeeActionPerformed

    private void lblAdminLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdminLoginMouseClicked
        controller.changeForAdmin();
    }//GEN-LAST:event_lblAdminLoginMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup SelectRegistry;
    public javax.swing.JButton btnLogin;
    private javax.swing.JLabel imgWallpaper;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblAdminLogin;
    public javax.swing.JLabel lblPassword;
    public javax.swing.JLabel lblRegister;
    public javax.swing.JLabel lblUserName;
    public javax.swing.JRadioButton rdbCustomer;
    public javax.swing.JRadioButton rdbEmployee;
    public javax.swing.JTextField txpPassword;
    public javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
